web:
  build:
    context: .
    dockerfile: Dockerfile-Java
  ports:
    - "8081:8080"
  depends_on:
    - db

db:
  build:
    context: .
    dockerfile: Dockerfile-Postgres
  expose:
    - "5432"
  volumes_from:
    - app-db-data

app-db-data:
  image: cogniteev/echo
  command: echo 'Data Container for PostgreSQL'
  volumes:
    - /var/lib/postgresql/data
